##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += diskio.o
obj-y += ff.o
obj-y += option/cc936.o
