##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

CCFLAGS += -I$(dir)/../inc
CCFLAGS += -I$(dir)/../../inside-include

obj-y = misc.o
#obj-y += stm32f10x_adc.o
#obj-y += stm32f10x_bkp.o
#obj-y += stm32f10x_can.o
#obj-y += stm32f10x_cec.o
#obj-y += stm32f10x_crc.o
#obj-y += stm32f10x_dac.o
#obj-y += stm32f10x_dbgmcu.o
obj-y += stm32f10x_dma.o
obj-y += stm32f10x_exti.o
#obj-y += stm32f10x_flash.o
#obj-y += stm32f10x_fsmc.o
obj-y += stm32f10x_gpio.o
obj-y += stm32f10x_i2c.o
#obj-y += stm32f10x_iwdg.o
#obj-y += stm32f10x_pwr.o
obj-y += stm32f10x_rcc.o
#obj-y += stm32f10x_rtc.o
#obj-y += stm32f10x_sdio.o
obj-y += stm32f10x_spi.o
#obj-y += stm32f10x_tim.o
obj-y += stm32f10x_usart.o
#obj-y += stm32f10x_wwdg.o


