##############################################
# Copyright (C) 2024-2024胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

CCFLAGS += -Iapp/server/ndk

obj-y += cmd
obj-y += protocol
obj-y += usb

obj-y += ndk.o
