##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-$(CONFIG_DISPLAY_SERVER) += display
obj-$(CONFIG_CONNECT_SERVER) += connect
