##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
#
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-$(CONFIG_STM32PWM) += stm32_pwm.o
obj-$(CONFIG_NK60_V2_LED) += nk60_v2_led.o
