##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-$(CONFIG_USB_HID) = hid.o
obj-$(CONFIG_USB_WINUSB) += winusb.o
obj-$(CONFIG_USB_CDC) += cdc.o
