##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

DEFINES += -DSTM32F10X_HD -DUSE_STDPERIPH_DRIVER
