##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

# ARM 架构特定编译选项

# 基础架构标志
ARCH_FLAGS := -march=armv7-m

# CPU 特定标志
ifeq ($(CONFIG_ARM_CORTEX_M3),y)
    ARCH_FLAGS := -march=armv7-m -mcpu=cortex-m3
endif

ifeq ($(CONFIG_ARM_CORTEX_M4),y)
    ARCH_FLAGS := -march=armv7e-m -mcpu=cortex-m4
    # Cortex-M4 支持硬件浮点
    FP_FLAGS := -mfloat-abi=hard -mfpu=fpv4-sp-d16
endif

ifeq ($(CONFIG_ARM_CORTEX_A7),y)
    ARCH_FLAGS := -march=armv7-a -mcpu=cortex-a7
    FP_FLAGS := -mfloat-abi=hard -mfpu=neon-vfpv4
endif

# Thumb-2 指令集支持
ifeq ($(CONFIG_THUMB2_KERNEL),y)
    ARCH_FLAGS += -mthumb
endif

# 编译器特定的 ARM 选项
ifeq ($(CONFIG_CC_IS_CLANG),y)
    # Clang ARM 特定选项
    ARCH_FLAGS += -fno-integrated-as
    # Clang 对某些 ARM 特性的处理
    ifneq ($(CONFIG_ARM_CORTEX_A7),y)
        # 对于 Cortex-M 系列，禁用全局合并优化
        ARCH_FLAGS += -mno-global-merge
    endif
else
    # GCC ARM 特定选项
    ARCH_FLAGS += -mno-sched-prolog
    # GCC 特定的 ARM 优化
    ARCH_FLAGS += -fno-delete-null-pointer-checks
endif

# 定义架构相关的宏
DEFINES += -D__ARM__
ifeq ($(CONFIG_THUMB2_KERNEL),y)
    DEFINES += -D__THUMB2__
endif

# 链接脚本
ifeq ($(CONFIG_ARM_CORTEX_M3),y)
    LDSCRIPT += arch/arm/kernel/cortex-m3.ld.S
endif

ifeq ($(CONFIG_ARM_CORTEX_M4),y)
    LDSCRIPT += arch/arm/kernel/cortex-m4.ld.S
endif

ifeq ($(CONFIG_ARM_CORTEX_A7),y)
    LDSCRIPT += arch/arm/kernel/cortex-a7.ld.S
endif
