##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += display_server.o
obj-$(CONFIG_DISPLAY_SERVER_DEMO) += draw_demo.o
