##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

CCFLAGS += -I$(dir)/../inc
CCFLAGS += -I$(dir)/../../inside-include

obj-y = misc.o
#obj-y += stm32f4xx_adc.o
#obj-y += stm32f4xx_can.o
#obj-y += stm32f4xx_crc.o
#obj-y += stm32f4xx_cryp_aes.o
#obj-y += stm32f4xx_cryp_des.o
#obj-y += stm32f4xx_cryp_tdes.o
#obj-y += stm32f4xx_cryp.o
#obj-y += stm32f4xx_dac.o
obj-y += stm32f4xx_dbgmcu.o
#obj-y += stm32f4xx_dcmi.o
obj-y += stm32f4xx_dma.o
obj-y += stm32f4xx_dma2d.o
obj-y += stm32f4xx_exti.o
#obj-y += stm32f4xx_flash_ramfunc.o
#obj-y += stm32f4xx_flash.o
#obj-y += stm32f4xx_fsmc.o
obj-y += stm32f4xx_gpio.o
#obj-y += stm32f4xx_hash_md5.o
#obj-y += stm32f4xx_hash_sha1.o
#obj-y += stm32f4xx_hash.o
obj-y += stm32f4xx_i2c.o
#obj-y += stm32f4xx_iwdg.o
obj-y += stm32f4xx_pwr.o
obj-y += stm32f4xx_rcc.o
#obj-y += stm32f4xx_rng.o
obj-y += stm32f4xx_rtc.o
#obj-y += stm32f4xx_sai.o
#obj-y += stm32f4xx_sdio.o
obj-y += stm32f4xx_spi.o
obj-y += stm32f4xx_syscfg.o
obj-y += stm32f4xx_tim.o
obj-y += stm32f4xx_usart.o
#obj-y += stm32f4xx_wwdg.o


