##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += printk
obj-y += cpu
obj-y += mm

obj-y += console.o
obj-y += sleep.o
obj-y += irq.o
obj-y += spinlock.o
obj-y += pid.o
