##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += printk
obj-y += cpu
obj-y += mm
obj-y += sch

obj-y += kernel.o
obj-y += console.o
obj-y += sleep.o
obj-y += irq.o
obj-y += spinlock.o
obj-y += pid.o
obj-y += boot.o
obj-y += timer.o
obj-y += sem.o
obj-y += mutex.o
obj-y += msg_queue.o
obj-y += sys.o
