##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-$(CONFIG_TEST_APP) += test.o
obj-$(CONFIG_KEYBOARD) += keyboard.o
