##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += vfs.o
obj-y += ramfs.o
obj-y += procfs.o
obj-y += sysfs.o
obj-$(CONFIG_FATFS) += fatfs
