##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

board := $(shell echo $(CONFIG_BOARD) | sed 's/\"//g')

obj-y := $(board)
