##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += base
obj-y += char
obj-y += block
obj-y += key
obj-y += misc
obj-y += spi
obj-y += i2c
obj-$(CONFIG_USB) += usb
obj-y += display
obj-$(CONFIG_STM32F4XX) += stm32f4xx
