##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += base
obj-y += key
obj-y += misc
obj-y += spi
obj-$(CONFIG_USB) += usb
