##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += mm_block.o
obj-y += mm_core.o
obj-y += mm.o
obj-y += mm_buddy.o
obj-y += mm_node.o
obj-y += mm_page.o
