##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-$(CONFIG_RGB_MATRIX) += rgb-matrix.o
obj-$(CONFIG_ZJ_TFTLCD) += zj-tft-lcd.o
obj-$(CONFIG_ST7789_LCD) += st7789-lcd.o
obj-$(CONFIG_SSD1106_OLED) += ssd1106-oled.o
