##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-$(CONFIG_NK60_DISPLAY_SERVER) += nk60_display_server.o
