##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
#
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-$(CONFIG_SPI_595) = spi-74hc595.o
obj-$(CONFIG_NK60_V2_W25QXX) += nk60_v2-w25qxx.o
obj-$(CONFIG_SPI_SDCARD) = spi-sdcard.o
