##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-$(CONFIG_SPI_595) = spi-74hc595.o
obj-$(CONFIG_SPI_W25QXX) += spi-w25qxx.o
