##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

board := $(shell echo $(CONFIG_BOARD) | sed 's/\"//g')

FP_FLAGS	= -msoft-float
ARCH_FLAGS	= -mthumb -mcpu=cortex-m3
OOCD_TARGET	:= stm32f1x
OOCDCFG := board/$(board)/openocd.cfg
LDSCRIPT += board/$(board)/nos_kernel.ld.S
DEFINES += -DSTM32F10X_HD -DUSE_STDPERIPH_DRIVER
INC_DIR += -Iboard/$(board)/include
SVD_CFG := board/$(board)/STM32F103xx.svd

QEMU_CMD := qemu-system-arm -M nos_stm32 -nographic
