##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
#
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

#obj-$(CONFIG_KEYBOARD) += key_action.o

obj-$(CONFIG_NK60_V1_KEY) += keyboard.o
obj-$(CONFIG_NK60_V2_KEY) += nk60_v2_key.o
