##############################################
# Copyright (C) 2018 胡启航<Hu Qihang>
#
# Author: wkcs
# 
# Email: hqh2030@gmail.com, huqihan@live.com
##############################################

obj-$(CONFIG_KEYBOARD) = keyboard.o
obj-$(CONFIG_KEYBOARD) += key_action.o
