##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

TARGET = nos

RM := rm -rf

#定义工具链
PREFIX		:= arm-none-eabi-
CC		    := $(PREFIX)gcc
CXX		    := $(PREFIX)g++
LD		    := $(PREFIX)ld
AR		    := $(PREFIX)ar
AS		    := $(PREFIX)as
OBJCOPY		:= $(PREFIX)objcopy
OBJDUMP		:= $(PREFIX)objdump
SIZE        := $(PREFIX)size
GDB		    := gdb-multiarch

PYTHON := python3

OPTSRC = -O2

TARGET_HEX = $(out-dir)/$(TARGET).hex
TARGET_SIZE = $(out-dir)/$(TARGET).size
TARGET_BIN = $(out-dir)/$(TARGET).bin
TARGET_ELF = $(out-dir)/$(TARGET).elf
TARGET_LIST = $(out-dir)/$(TARGET).list
TARGET_MAP = $(out-dir)/$(TARGET).map
TARGET_IMG = $(out-dir)/$(TARGET).img

#头文件文件目录
INC_DIR += -Iinclude
INC_DIR += -Iarch/$(ARCH)/include
INC_DIR += -I$(out-dir)/include
INC_DIR += -Iapp/lua/lib
INC_DIR += -Iapp/lvgl/lib

CCFLAGS = $(ARCH_FLAGS)
CCFLAGS += $(FP_FLAGS)
CCFLAGS += $(OPTSRC)
CCFLAGS += -fmessage-length=0 -fsigned-char -ffunction-sections
CCFLAGS += -fdata-sections -ffreestanding -fno-move-loop-invariants
CCFLAGS += -g3
CCFLAGS += -Wno-unused-parameter
CCFLAGS += -Wno-unused-function
CCFLAGS += -Wno-unused-variable
CCFLAGS += -Wno-array-bounds
CCFLAGS += -Wa,-mimplicit-it=thumb
#CCFLAGS += -nostdinc
CCFLAGS += -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c
CCFLAGS += $(INC_DIR)
CCFLAGS += $(DEFINES)

ASFLAGS = $(ARCH_FLAGS)
ASFLAGS += $(FP_FLAGS)
ASFLAGS += $(OPTSRC)
ASFLAGS += -fmessage-length=0 -fsigned-char -ffunction-sections
ASFLAGS += -fdata-sections -ffreestanding -fno-move-loop-invariants
ASFLAGS += -Wall -Wextra -Werror -x assembler-with-cpp
ASFLAGS += -g3
ASFLAGS += -Wa,-mimplicit-it=thumb
ASFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c
ASFLAGS += $(INC_DIR)
ASFLAGS += $(DEFINES)

LDFLAGS = $(ARCH_FLAGS)
LDFLAGS += $(FP_FLAGS)
LDFLAGS += -nostdinc
LDFLAGS += -Wl,--start-group -Wl,--end-group -Wl,-cref,-u,Reset_Handler
LDFLAGS += -Wl,-gc-sections
LDFLAGS += -Wl,-Map=$(TARGET_MAP)
LDFLAGS += -Wl,--defsym=malloc_getpagesize_P=0x80

LDFLAGS-LIB = -lgcc -lc -lm