#!/usr/bin/env python3
import sys
import re


def generate_kallsyms(map_file, output_file):
    symbols = []

    with open(map_file, "r") as f:
        for line in f:
            # nm output format: address type name
            parts = line.strip().split()
            if len(parts) < 3:
                continue

            addr_str = parts[0]
            type_char = parts[1]
            name = parts[2]

            # Only keep function symbols (text section)
            if type_char.upper() in ["T", "t"]:
                symbols.append((int(addr_str, 16), name))

    # Sort by address
    symbols.sort(key=lambda x: x[0])

    with open(output_file, "w") as f:
        f.write("/* Auto-generated by scripts/mkkallsyms.py */\n")
        f.write("#include <kernel/kallsyms.h>\n\n")

        # Write symbol table
        f.write("const struct kallsym_entry kallsyms_table[] = {\n")
        for addr, name in symbols:
            f.write(f'    {{ 0x{addr:08x}, "{name}" }},\n')
        f.write("    { 0, 0 }\n")  # Sentinel
        f.write("};\n\n")

        f.write(f"const unsigned int kallsyms_num = {len(symbols)};\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: mkkallsyms.py <nm_output> <output_c_file>")
        sys.exit(1)

    generate_kallsyms(sys.argv[1], sys.argv[2])
