##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += string.o
obj-y += vsprintf.o
obj-y += kfifo.o
