##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

CCFLAGS += -I$(dir)/../inside-include
CCFLAGS += -I$(dir)/../drivers/inc

obj-y = stm32f1xx_hal_pcd_ex.o
obj-y += stm32f1xx_hal_pcd.o
obj-y += stm32f1xx_ll_usb.o




