##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y = lib
obj-y += lvgl_test.o