##############################################
# Copyright (C) 2024-2024 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

obj-y += lapi.o
obj-y += lcode.o
obj-y += lctype.o
obj-y += ldebug.o
obj-y += ldo.o
obj-y += ldump.o
obj-y += lfunc.o
obj-y += lgc.o
obj-y += llex.o
obj-y += lmem.o
obj-y += lobject.o
obj-y += lopcodes.o
obj-y += lparser.o
obj-y += lstate.o
obj-y += lstring.o
obj-y += ltable.o
obj-y += ltm.o
obj-y += lundump.o
obj-y += lvm.o
obj-y += lzio.o
obj-y += lauxlib.o
obj-y += lbaselib.o
obj-y += lcorolib.o
obj-y += ldblib.o
obj-y += liolib.o
obj-y += lmathlib.o
obj-y += loadlib.o
obj-y += loslib.o
obj-y += lstrlib.o
obj-y += ltablib.o
obj-y += lutf8lib.o
obj-y += linit.o
