##############################################
# Copyright (C) 2023-2023 胡启航<Nick Hu>
#
# Author: 胡启航<Nick Hu>
#
# Email: huqihan@live.com
##############################################

board := $(shell echo $(CONFIG_BOARD) | sed 's/\"//g')

FP_FLAGS	= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS	= -mthumb -mcpu=cortex-m4
OOCD_TARGET	:= stm32f4x
OOCDCFG := board/$(board)/openocd.cfg
LDSCRIPT += board/$(board)/nos_kernel.ld.S
DEFINES += -DSTM32F401xx -DUSE_STDPERIPH_DRIVER -D__VFP_FP__
INC_DIR += -Iboard/$(board)/include
INC_DIR += -Iboard/$(board)/drivers/inc
SVD_CFG := board/$(board)/STM32F401.svd